name: Amiga OS4

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: hitman-codehq/RADRunner
          path: RADRunner
      - name: Checkout StdFuncs
        uses: actions/checkout@v3
        with:
          repository: hitman-codehq/StdFuncs
          path: StdFuncs
      - name: Download Libraries
        run: |
          gh run download --repo hitman-codehq/StdFuncs --name Amiga-Libraries-OS4 --dir StdFuncs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: hitman-codehq/Amiga-Build-OS4@v1
        env:
          PREFIX: ppc-amigaos-
        with:
          command: make
          directory: RADRunner
      - name: Build Debug
        uses: hitman-codehq/Amiga-Build-OS4@v1
        env:
          PREFIX: ppc-amigaos-
        with:
          command: make DEBUG=1
          directory: RADRunner
      - name: Archive Executables
        uses: actions/upload-artifact@v3
        with:
          name: Amiga-Executables-OS4
          path: |
            RADRunner/Debug_OS4/RADRunner
            RADRunner/Release_OS4/RADRunner
      - name: Prepare Release Files
        run: |
          echo -e "ref: $GITHUB_REF \ncommit: $GITHUB_SHA\nbuild: $(date +"%Y-%m-%dT%H:%M:%SZ")" > ReleaseInfo.txt
          echo -e "platform:" $(uname -a) >> ReleaseInfo.txt
          cp -a RADRunner/Debug_OS4/RADRunner ./RADRunner.debug
      - name: Update Latest Build
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest_amiga_os4
          name: "Amiga OS4 Latest Build $$"
          prerelease: true
          body: "This is a build of the latest code pushed to GitHub. It has received basic local testing but is
            not an official release and is not guaranteed to function correctly"
          files: |
            RADRunner.debug
            RADRunner/Release_OS4/RADRunner
            ReleaseInfo.txt
