name: Windows

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout StdFuncs
        uses: actions/checkout@v3
        with:
          repository: hitman-codehq/StdFuncs
          path: StdFuncs
      - name: Download Libraries
        run: |
          mv StdFuncs ..
          gh run download --repo hitman-codehq/StdFuncs --name Windows-Libraries --dir ../StdFuncs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: "16.0"
      - name: Build
        run: |
          msbuild /p:Configuration=Release /p:Platform=x86
          msbuild /p:Configuration=Release /p:Platform=x64
      - name: Build Debug
        run: |
          msbuild /p:Configuration=Debug /p:Platform=x86
          msbuild /p:Configuration=Debug /p:Platform=x64
      - name: Archive Executables
        uses: actions/upload-artifact@v3
        with:
          name: Windows-Executables
          path: |
            Win32/Debug/*.exe
            x64/Debug/*.exe
            Win32/Release/*.exe
            x64/Release/*.exe
      - name: Prepare Release Files
        run: |
          echo "ref: $GITHUB_REF `ncommit: $GITHUB_SHA`nbuild: $(date +"%Y-%m-%dT%H:%M:%SZ")" > ReleaseInfo.txt
          dir
          copy x64/Debug/RADRunner.exe ./RADRunner.debug.exe
          copy x64/Release/RADRunner.exe .
      - name: Update Latest Build
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest_windows
          name: "Windows Latest Build $$"
          prerelease: true
          body: "This is a build of the latest code pushed to GitHub. It has received basic local testing but is
            not an official release and is not guaranteed to function correctly"
          files: |
            RADRunner.debug.exe
            RADRunner.exe
            ReleaseInfo.txt
